import fs from "fs-extra";
import path from "path";
import { exec } from "child_process";
import util from "util";

const execAsync = util.promisify(exec);

const FIX_RULES = {
  LOOSE_EQUALITY: (line) => line.replace(/([^=!])==([^=])/g, "$1===$2"),
  MISSING_AWAIT: (line) => {
    if (/^\s*await\b/.test(line)) return line;
    const indent = (line.match(/^\s*/) || [""])[0];
    return `${indent}await ${line.trimStart()}`;
  },
  INNER_HTML_XSS: (line) => line.replace(/innerHTML/g, "textContent"),
  SYNC_IO: (line) => line.replace(/readFileSync/g, "await fs.promises.readFile"),
  SET_INTERVAL_LEAK: (line) => `${line} // TODO: add clearInterval()`,
  INSECURE_HASH: (line) => line.replace(/\bmd5\b/gi, "bcrypt"),
  RAW_SQL_QUERY: (line) => `// FIX: Use parameterized query\n${line}`
};

const RULE_ALIASES = [
  { pattern: /^LOOSE_EQUALITY/, key: "LOOSE_EQUALITY" },
  { pattern: /^MISSING_AWAIT(_OR_ASYNC)?/, key: "MISSING_AWAIT" },
  { pattern: /^(XSS_DOM|INNER_HTML_XSS)/, key: "INNER_HTML_XSS" },
  { pattern: /^SYNC_IO/, key: "SYNC_IO" },
  { pattern: /^(UNMANAGED_TIMER|MEMORY_LEAK_TIMER|SET_INTERVAL_LEAK)/, key: "SET_INTERVAL_LEAK" },
  { pattern: /^INSECURE_CRYPTO/, key: "INSECURE_HASH" },
  { pattern: /^SQL_INJECTION/, key: "RAW_SQL_QUERY" }
];

const normalizeId = (id = "") => {
  const raw = String(id).trim().toUpperCase();

  for (const alias of RULE_ALIASES) {
    if (alias.pattern.test(raw)) return alias.key;
  }

  return raw;
};

const normalizeSeverity = (severity = "") => String(severity).trim().toLowerCase();

const loadFindingsFromDisk = async (repoPath) => {
  const candidates = [
    path.join(repoPath, "memory", "final-report.json"),
    path.join(repoPath, "memory", "findings.json")
  ];

  for (const file of candidates) {
    if (!(await fs.pathExists(file))) continue;

    const data = await fs.readJson(file);
    if (Array.isArray(data?.findings)) {
      return data.findings;
    }
  }

  const merged = [];
  const splitFiles = ["security.json", "logic.json", "performance.json", "ui.json"];

  for (const name of splitFiles) {
    const file = path.join(repoPath, "memory", name);
    if (!(await fs.pathExists(file))) continue;

    const data = await fs.readJson(file);
    if (Array.isArray(data?.findings)) {
      merged.push(...data.findings);
    }
  }

  return merged;
};

const applyFixToFile = async (filePath, lineNumber, fixFn, dryRun = false) => {
  if (!Number.isInteger(lineNumber) || lineNumber <= 0) return { applied: false, reason: "invalid-line" };

  if (!(await fs.pathExists(filePath))) {
    return { applied: false, reason: "missing-file" };
  }

  const content = await fs.readFile(filePath, "utf8");
  const lines = content.split(/\r?\n/);

  if (!lines[lineNumber - 1]) {
    return { applied: false, reason: "line-out-of-range" };
  }

  const original = lines[lineNumber - 1];
  const fixed = fixFn(original);

  if (!fixed || fixed === original) {
    return { applied: false, reason: "no-change" };
  }

  lines[lineNumber - 1] = fixed;

  if (!dryRun) {
    await fs.writeFile(filePath, lines.join("\n"), "utf8");
  }

  return {
    applied: true,
    original,
    fixed
  };
};

const runGit = async (command, cwd) => {
  const { stdout, stderr } = await execAsync(command, { cwd });
  if (stderr && !stderr.toLowerCase().includes("warning")) {
    throw new Error(stderr);
  }
  return stdout.trim();
};

const createPullRequest = async ({ repo, branch, base, token }) => {
  const response = await fetch(`https://api.github.com/repos/${repo}/pulls`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      title: "Auto Fix: Divya Drishti Remediation",
      head: branch,
      base,
      body: "Automated remediation generated by Divya Drishti Auto-Fix Engine."
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Failed to create pull request: ${text}`);
  }

  return response.json();
};

const commitAndPush = async ({ repoPath, push = false, createPr = false }) => {
  await runGit("git rev-parse --is-inside-work-tree", repoPath);

  const branch = `autofix/${Date.now()}`;
  await runGit(`git checkout -b ${branch}`, repoPath);
  await runGit("git add .", repoPath);
  await runGit('git commit -m "chore(autofix): apply automated fixes"', repoPath);

  let pushed = false;
  let pr = null;

  if (push) {
    await runGit(`git push origin ${branch} --set-upstream`, repoPath);
    pushed = true;
  }

  if (createPr && pushed) {
    const repo = process.env.GITHUB_REPOSITORY;
    const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;

    if (repo && token) {
      const base = process.env.GITHUB_BASE_REF || "main";
      pr = await createPullRequest({ repo, branch, base, token });
    }
  }

  return {
    branch,
    pushed,
    pr: pr?.html_url || null
  };
};

export const runAutoFix = async (repoPath, options = {}) => {
  const {
    findings: inputFindings,
    includeCritical = false,
    dryRun = false,
    commit = false,
    push = false,
    createPr = false
  } = options;

  const targetRepo = path.resolve(repoPath || process.cwd());

  console.log("Starting Auto-Fix Engine...");

  const findings = Array.isArray(inputFindings) && inputFindings.length
    ? inputFindings
    : await loadFindingsFromDisk(targetRepo);

  if (!findings.length) {
    console.log("No findings found.");
    return {
      fixedCount: 0,
      skippedCount: 0,
      totalFindings: 0,
      changes: [],
      git: null
    };
  }

  let fixedCount = 0;
  let skippedCount = 0;
  const changes = [];

  for (const finding of findings) {
    const ruleId = normalizeId(finding.id || "");
    const fixFn = FIX_RULES[ruleId];

    if (!fixFn) {
      skippedCount += 1;
      continue;
    }

    if (!finding.file || !finding.line) {
      skippedCount += 1;
      continue;
    }

    if (!includeCritical && normalizeSeverity(finding.severity) === "critical") {
      console.log(`Manual review required for critical finding: ${finding.issue || finding.id}`);
      skippedCount += 1;
      continue;
    }

    const filePath = path.isAbsolute(finding.file)
      ? finding.file
      : path.resolve(targetRepo, finding.file);

    try {
      const result = await applyFixToFile(filePath, Number(finding.line), fixFn, dryRun);

      if (!result.applied) {
        skippedCount += 1;
        continue;
      }

      fixedCount += 1;
      changes.push({
        id: finding.id,
        file: path.relative(targetRepo, filePath),
        line: finding.line,
        issue: finding.issue,
        before: result.original,
        after: result.fixed
      });

      console.log(`Fixed: ${finding.issue || finding.id} (${finding.file}:${finding.line})`);
    } catch (err) {
      console.log(`Failed: ${finding.file} (${err.message})`);
      skippedCount += 1;
    }
  }

  const summaryPath = path.join(targetRepo, "memory", "auto-fix-report.json");
  await fs.ensureDir(path.dirname(summaryPath));
  await fs.writeJson(summaryPath, {
    timestamp: new Date().toISOString(),
    totalFindings: findings.length,
    fixedCount,
    skippedCount,
    dryRun,
    changes
  }, { spaces: 2 });

  let git = null;
  if (commit && !dryRun && fixedCount > 0) {
    git = await commitAndPush({
      repoPath: targetRepo,
      push,
      createPr
    });
  }

  console.log(`Auto-fix completed. Total fixes: ${fixedCount}`);

  return {
    fixedCount,
    skippedCount,
    totalFindings: findings.length,
    changes,
    reportPath: summaryPath,
    git
  };
};
