import { exec } from "child_process";
import util from "util";
import fs from "fs-extra";
import path from "path";
import crypto from "crypto";

const execAsync = util.promisify(exec);

// -------------------------
// Helpers
// -------------------------
const runGit = async (cmd) => {
  const { stdout, stderr } = await execAsync(cmd);
  if (stderr && !stderr.includes("warning")) {
    throw new Error(stderr);
  }
  return stdout.trim();
};

const generateBranchName = () => `audit/divya-${Date.now()}`;

const generateCommitMessage = () =>
  `chore(audit): add automated audit report`;

const generateReportHash = (report) =>
  crypto.createHash("sha256").update(report).digest("hex").slice(0, 8);

const isProtectedBranch = (branch) =>
  ["main", "master", "production"].includes(branch);

// -------------------------
// Repo Status Logger
// -------------------------
const getRepoStatus = async () => {
  return {
    branch: await runGit("git rev-parse --abbrev-ref HEAD"),
    lastCommit: await runGit("git log -1 --pretty=format:%h %s"),
    status: await runGit("git status --short"),
    remote: await runGit("git remote -v"),
    aheadBehind: await runGit("git status -sb"),
  };
};

// -------------------------
// Commit Signature Check
// -------------------------
const verifyCommitSignature = async () => {
  try {
    const result = await runGit("git log -1 --pretty=format:%G?");
    return {
      verified: result === "G",
      status: result
    };
  } catch {
    return {
      verified: false,
      status: "unknown"
    };
  }
};

// -------------------------
// GitHub PR (optional)
// -------------------------
const createPullRequest = async ({
  repo,
  title,
  head,
  base,
  body,
  token
}) => {
  const res = await fetch(`https://api.github.com/repos/${repo}/pulls`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      title,
      head,
      base,
      body
    })
  });

  if (!res.ok) {
    throw new Error("Failed to create PR");
  }

  return res.json();
};

// -------------------------
// MAIN FUNCTION
// -------------------------
export const gitManager = async (report, options = {}) => {
  const {
    repoPath = process.cwd(),
    outputFile = "AUDIT_REPORT.md",
    push = false,
    createPR = false,
    github = {},
    signCommit = false,
    enforceSignedCommit = false
  } = options;

  try {
    process.chdir(repoPath);

    // 1. Validate repo
    await runGit("git rev-parse --is-inside-work-tree");

    const initialStatus = await getRepoStatus();

    // 2. Branch check
    let currentBranch = initialStatus.branch;

    if (isProtectedBranch(currentBranch)) {
      const newBranch = generateBranchName();
      await runGit(`git checkout -b ${newBranch}`);
      currentBranch = newBranch;
    }

    // 3. Ensure clean repo
    if (initialStatus.status) {
      throw new Error("Working tree is not clean");
    }

    // 4. Write report
    const reportPath = path.join(repoPath, outputFile);
    await fs.writeFile(reportPath, report, "utf8");

    // 5. Stage only report
    await runGit(`git add ${outputFile}`);

    // 6. Commit
    const hash = generateReportHash(report);
    const commitMessage = `${generateCommitMessage()} [${hash}]`;

    const signFlag = signCommit ? "-S" : "";
    await runGit(`git commit ${signFlag} -m "${commitMessage}"`);

    // 7. Verify commit signature
    const signature = await verifyCommitSignature();

    if (enforceSignedCommit && !signature.verified) {
      throw new Error("Commit is not signed or signature invalid");
    }

    // 8. Push
    if (push) {
      await runGit(`git push origin ${currentBranch} --set-upstream`);
    }

    // 9. PR creation
    let prData = null;
    if (createPR && github.repo && github.token) {
      prData = await createPullRequest({
        repo: github.repo,
        title: "Automated Audit Report",
        head: currentBranch,
        base: github.base || "main",
        body: "Automated audit report generated by Divya Drishti.",
        token: github.token
      });
    }

    // 10. Diff + final status
    const diff = await runGit("git show");
    const finalStatus = await getRepoStatus();

    return {
      status: "success",
      branch: currentBranch,
      commit: await runGit("git rev-parse --short HEAD"),
      report_file: outputFile,
      pushed: push,
      pull_request: prData ? prData.html_url : null,
      signature,
      repo_status: {
        before: initialStatus,
        after: finalStatus
      },
      diff
    };

  } catch (err) {
    return {
      status: "failed",
      error: err.message
    };
  }
};